### ISSUE TITLE
Resolve type checker bugs

### ISSUE THREAD

**Issue by Flumble** [wandernauta/viskell#170]
The type checker right now is not bug-free. The main bug is that it crashes on recursion.

Some visual bugs:
- some functions like scanl *visually* have a signature (a -> a -> a) -> a -> [a] -> [a] when there's no wire connected (to fill in a type variable) and they are uncurried, though their actual signature is (b->a->b)->b->[a]->[b]
- some functions show a number as type variable instead of a letter (this number also increases with every change, so look into that)
- when currying/uncurrying a function for which the output is already attached to another node, this node may become invalid (shown with a red line and a warning sign), but it will not become *visually* valid again after moving the knot back.
- connecting an output with a second wire to a tree only *visually* updates 1 occurence of that type. For example, connect a True and an (==) to an (||) as inputs, then connect the True to the (==) as input –the type will read Bool only at the argument where the True is connected.

**Comment by comonoidial** [comment]
While recursion is not supported now,  crashing should never happen.

Bug 1: is caused by the type variable implementation, and is fixed in my improved_types branch.
Bug 2: the number thing is solved by pull request #169, however the fast increasing typevar IDs shows that the UI is invoking the typechecker way too often.
Bug 3: looks like a true UI bug.
Bug 4: seems to be solved in the improved_types branch, but as soon as wires are disconnected it goes visually wrong again because not everything updates right.

Reproducing any of these bugs without using the UI in the unit tests would be appreciated.

**Comment by comonoidial** [comment]
Any bugs left with the now fully rewritten typechecker, except for error connections as mentioned in #183?
Did you find anything else with wrong types, @Flumble ?

**Comment by Flumble** [comment]
All the bugs are fixed except for a case resulting from scenario 4:
> connect a True and an (==) to an (||) as inputs, then connect the True to the (==) as input 

Viskell currently crashes (probably endless recursion, judging from the stack overflow) in an attempt to check this program in which a connection is made higher up in an expression tree (after which it is no longer a tree but a DAG). Note that this doesn't hold in general: for example, (type) manipulating a list and then zipping it with the original list works fine.

**Comment by comonoidial** [comment]
Fixed in #221.
